### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by ghost** [redomino/redomino.advancedkeyword#2]
When I install redomino.advancedkeyword with buildout I get the following error:

`Getting distribution for 'redomino.advancedkeyword'.
error: docs/HISTORY.txt: No such file or directory
An error occured when trying to install redomino.advancedkeyword 0.9. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
  Getting distribution for 'redomino.advancedkeyword'.
Error: Couldn't install: redomino.advancedkeyword 0.9`

Plone version is 4.1.5

Whitie

**Comment by davidemoro** [comment]
Confirmed, thanks

**Comment by davidemoro** [comment]
Closed. Fixed in 1.0 version, just released

**Comment by ghost** [comment]
Thanks
