### ISSUE TITLE
No subtags to choose

### ISSUE THREAD

**Issue by ghost** [redomino/redomino.advancedkeyword#3]
When I create a new tag 'what.ever', I have only 'what' in the list. In the keywordsmap it is shown correctly as nested list. The Page is also correctly tagged with 'what' and 'what.ever'.
When I create a new page (or edit an existing), I have no option to choose 'what.ever' as tag. The widget only shows 'what' with no option to expand anything.

I am using the current git sources with Plone 4.1.5. Javascript is activated (search the tags works).

Update:
It works as expected, but the icons are not shown in front of the supertags. If you click near the checkbox, the subtags expand or collapse. The issue is only that the icons are not shown.

Greets
Whitie

**Comment by davidemoro** [comment]
Confirmed, thanks!

**Comment by davidemoro** [comment]
Fixed but not released on pypi yet. Can you confirm the resolution please?

**Comment by ghost** [comment]
It's fixed. Thank you.
